<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sight;
use App\Models\Country;

class SightsTableSeeder extends Seeder
{
    public function run()
    {
        $sights = [
            [
                'country'        => 'France',
                'name'           => 'Eiffel Tower',
                'description'    => 'An architectural masterpiece and a symbol of France, the Eiffel Tower offers breathtaking panoramic views of Paris from its multiple observation decks. Its intricate iron lattice structure and dazzling nightly illuminations make it a must-see landmark.',
                'location'       => 'Paris, France',
                'category'       => 'Landmark',
                'opening_hours'  => '9 AM - 11 PM',
                'average_rating' => 4.7,
                'map_url'        => 'https://maps.app.goo.gl/wXQEk6uYHFadzo8Q8',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Italy',
                'name'           => 'Colosseum',
                'description'    => 'A stunning Roman amphitheater that once hosted gladiatorial contests and public spectacles, the Colosseum stands as a testament to ancient engineering. Its monumental arches, underground chambers, and storied past transport visitors back in time.',
                'location'       => 'Rome, Italy',
                'category'       => 'Historical Site',
                'opening_hours'  => '8 AM - 5 PM',
                'average_rating' => 4.3,
                'map_url'        => 'https://maps.app.goo.gl/qvVime4Ynpb3n7p86',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'United Kingdom',
                'name'           => 'Tower Bridge',
                'description'    => 'A historic bascule and suspension bridge spanning the River Thames, Tower Bridge is famed for its Victorian Gothic architecture and stunning panoramic views of London. The bridge’s walkways offer unique vistas of the city’s skyline and river traffic below.',
                'location'       => 'London, United Kingdom',
                'category'       => 'Landmark',
                'opening_hours'  => '10 AM - 6 PM',
                'average_rating' => 4.3,
                'map_url'        => 'https://maps.app.goo.gl/gx65mHcG34ugwRxs9',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Japan',
                'name'           => 'Fushimi Inari Shrine',
                'description'    => 'A mesmerizing Shinto shrine in Kyoto, Fushimi Inari is renowned for its thousands of vibrant vermillion torii gates. These gates create a winding path up Mount Inari, offering visitors a spiritual and scenic journey through lush forested slopes.',
                'location'       => 'Kyoto, Japan',
                'category'       => 'Religious Site',
                'opening_hours'  => 'Open 24 hours',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/ezNF7SFsimkEeutcA',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Egypt',
                'name'           => 'Pyramids of Giza',
                'description'    => 'One of the Seven Wonders of the Ancient World, the Pyramids of Giza stand as monumental tombs of the pharaohs. Their immense scale, precise construction, and the mysteries surrounding their creation continue to captivate visitors and historians alike.',
                'location'       => 'Giza, Egypt',
                'category'       => 'Historical Site',
                'opening_hours'  => '8 AM - 5 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/zVLhRG5TiqgC3FrCA',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Australia',
                'name'           => 'Sydney Opera House',
                'description'    => 'A world-renowned performing arts center and UNESCO World Heritage site, the Sydney Opera House is celebrated for its distinctive sail-like design. It hosts a wide array of cultural events and offers guided tours that reveal the building’s unique architectural features.',
                'location'       => 'Sydney, Australia',
                'category'       => 'Cultural Site',
                'opening_hours'  => '9 AM - 5 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/ZwohmMricigSmekN7',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Brazil',
                'name'           => 'Christ the Redeemer',
                'description'    => 'An iconic statue of Jesus Christ overlooking Rio de Janeiro, Christ the Redeemer is a symbol of Brazilian culture and spirituality. With its outstretched arms and panoramic city views, it remains one of the world’s most recognizable landmarks.',
                'location'       => 'Rio de Janeiro, Brazil',
                'category'       => 'Religious Site',
                'opening_hours'  => '8 AM - 6 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/33VSWH7hrTMKE7sL7',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'United States',
                'name'           => 'Grand Canyon',
                'description'    => 'Carved by the Colorado River over millions of years, the Grand Canyon is one of the most breathtaking natural wonders on Earth. Its vast, layered landscape offers dramatic vistas, challenging hiking trails, and unforgettable sunset views.',
                'location'       => 'Arizona, USA',
                'category'       => 'Natural Wonder',
                'opening_hours'  => 'Open 24 hours',
                'average_rating' => 5,
                'map_url'        => 'https://maps.app.goo.gl/xC9QpprAzfWpP3Dq8',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'United States',
                'name'           => 'Statue of Liberty',
                'description'    => 'A universal symbol of freedom and democracy, the Statue of Liberty stands proudly on Liberty Island in New York Harbor. Visitors can explore its museum, ascend to the pedestal, and enjoy panoramic views of Manhattan and the surrounding waterways.',
                'location'       => 'New York, USA',
                'category'       => 'Landmark',
                'opening_hours'  => '8:30 AM - 4 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'India',
                'name'           => 'Taj Mahal',
                'description'    => 'A majestic white marble mausoleum built by Emperor Shah Jahan in memory of his beloved wife, the Taj Mahal is renowned for its exquisite craftsmanship, intricate carvings, and tranquil reflecting pools. It stands as a timeless symbol of love and a masterpiece of Mughal architecture.',
                'location'       => 'Agra, India',
                'category'       => 'Historical Site',
                'opening_hours'  => '6 AM - 7 PM',
                'average_rating' => 4.8,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'China',
                'name'           => 'Great Wall of China',
                'description'    => 'An ancient fortification spanning thousands of miles, the Great Wall of China was built to protect the Chinese empire. Its watchtowers, rugged pathways, and stunning vistas showcase the ingenuity and resilience of an era long past.',
                'location'       => 'Northern China',
                'category'       => 'Historical Site',
                'opening_hours'  => '7 AM - 5 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Peru',
                'name'           => 'Machu Picchu',
                'description'    => 'Nestled high in the Andes, Machu Picchu is an ancient Incan citadel renowned for its well-preserved ruins and stunning mountain vistas. This UNESCO World Heritage site offers a captivating glimpse into Incan civilization with terraced fields and stone structures that blend harmoniously with nature.',
                'location'       => 'Cusco Region, Peru',
                'category'       => 'Historical Site',
                'opening_hours'  => '6 AM - 5 PM',
                'average_rating' => 4.9,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'United Kingdom',
                'name'           => 'Stonehenge',
                'description'    => 'A mysterious prehistoric monument in Wiltshire, England, Stonehenge features a circle of massive standing stones whose origins and astronomical alignments continue to intrigue researchers and visitors alike.',
                'location'       => 'Wiltshire, United Kingdom',
                'category'       => 'Historical Site',
                'opening_hours'  => '9 AM - 7 PM',
                'average_rating' => 4.2,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Canada',
                'name'           => 'Niagara Falls',
                'description'    => 'A natural spectacle straddling the border of Canada and the USA, Niagara Falls is famed for its powerful cascades and misty atmosphere. Visitors can take boat tours for an up-close view or admire the falls from panoramic observation decks.',
                'location'       => 'Ontario, Canada / New York, USA',
                'category'       => 'Natural Wonder',
                'opening_hours'  => '24/7',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Iceland',
                'name'           => 'Blue Lagoon',
                'description'    => 'A geothermal spa set in a rugged lava field, the Blue Lagoon in Iceland is known for its milky blue, mineral-rich waters. This unique destination offers a rejuvenating experience with spa treatments, geothermal pools, and stunning natural surroundings.',
                'location'       => 'Grindavík, Iceland',
                'category'       => 'Natural Wonder',
                'opening_hours'  => '8 AM - 8 PM',
                'average_rating' => 4.7,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Spain',
                'name'           => 'Sagrada Familia',
                'description'    => 'An iconic basilica in Barcelona designed by Antoni Gaudí, the Sagrada Familia is celebrated for its intricate facades, towering spires, and a stunning interior that resembles a forest of stone columns. Despite being under construction for over a century, its unique blend of Gothic and Art Nouveau styles continues to inspire awe.',
                'location'       => 'Barcelona, Spain',
                'category'       => 'Religious Site',
                'opening_hours'  => '9 AM - 8 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            // Additional new sights
            [
                'country'       => 'France',
                'name'          => 'Louvre Museum',
                'description'   => 'The world-renowned Louvre Museum in Paris houses thousands of works of art, including the Mona Lisa and Venus de Milo. Its extensive collections span centuries and cultures, offering visitors an unparalleled journey through art and history.',
                'location'      => 'Paris, France',
                'category'      => 'Museum',
                'opening_hours' => '9 AM - 6 PM',
                // average_rating intentionally omitted to default to 0
                'map_url'       => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'         => null,
                'submitted_by'  => 1,
                'visible'       => true,
            ],
            [
                'country'        => 'France',
                'name'           => 'Notre Dame Cathedral',
                'description'    => 'A masterpiece of French Gothic architecture, Notre Dame Cathedral is famous for its intricate façade, stunning stained glass, and centuries of history. Even during restoration, its cultural significance endures.',
                'location'       => 'Paris, France',
                'category'       => 'Religious Site',
                'opening_hours'  => '8 AM - 6:45 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'United Arab Emirates',
                'name'           => 'Burj Khalifa',
                'description'    => 'The tallest building in the world, Burj Khalifa in Dubai offers unparalleled views of the city. Its futuristic design and record-breaking height make it a landmark of modern architecture.',
                'location'       => 'Dubai, UAE',
                'category'       => 'Landmark',
                'opening_hours'  => '8 AM - 10 PM',
                'average_rating' => 4.8,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Japan',
                'name'           => 'Mount Fuji',
                'description'    => 'Japan\'s tallest and most sacred mountain, Mount Fuji is renowned for its symmetrical cone and serene beauty. It attracts climbers and nature lovers alike with its stunning vistas and cultural significance.',
                'location'       => 'Honshu, Japan',
                'category'       => 'Natural Wonder',
                'opening_hours'  => 'Open 24 hours',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Australia',
                'name'           => 'Uluru',
                'description'    => 'A massive sandstone monolith in Australia\'s Red Centre, Uluru is a sacred site known for its dramatic color changes at sunrise and sunset. It offers visitors a deep connection to Aboriginal culture and the vast Outback landscape.',
                'location'       => 'Northern Territory, Australia',
                'category'       => 'Natural Wonder',
                'opening_hours'  => 'Sunrise to Sunset',
                // average_rating intentionally omitted to default to 0
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Cambodia',
                'name'           => 'Angkor Wat',
                'description'    => 'Angkor Wat is a sprawling temple complex and the crown jewel of Cambodia. Known for its intricate carvings and vast scale, it stands as a testament to the genius of Khmer architecture and draws visitors from around the globe.',
                'location'       => 'Siem Reap, Cambodia',
                'category'       => 'Historical Site',
                'opening_hours'  => '5 AM - 6 PM',
                'average_rating' => 4.9,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Greece',
                'name'           => 'Acropolis of Athens',
                'description'    => 'Perched on a rocky outcrop above Athens, the Acropolis is a timeless symbol of ancient Greek civilization. Home to the Parthenon and other classical monuments, it offers a profound glimpse into the cultural and architectural achievements of antiquity.',
                'location'       => 'Athens, Greece',
                'category'       => 'Historical Site',
                'opening_hours'  => '8 AM - 8 PM',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Greece',
                'name'           => 'Santorini Cliffs',
                'description'    => 'The iconic whitewashed cliffs of Santorini, Greece, overlook the deep blue Aegean Sea. Famous for its breathtaking sunsets and charming villages, this scenic view is a favorite among travelers seeking a blend of natural beauty and Mediterranean culture.',
                'location'       => 'Santorini, Greece',
                'category'       => 'Scenic View',
                'opening_hours'  => 'Open 24 hours',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
            [
                'country'        => 'Canada',
                'name'           => 'Banff National Park',
                'description'    => 'A pristine wilderness area in the Canadian Rockies, Banff National Park is celebrated for its turquoise glacial lakes, rugged mountains, and abundant wildlife. It offers a serene escape into nature and is a haven for outdoor enthusiasts.',
                'location'       => 'Alberta, Canada',
                'category'       => 'Natural Wonder',
                'opening_hours'  => 'Open 24 hours',
                'average_rating' => 0,
                'map_url'        => 'https://maps.app.goo.gl/EXAMPLE',
                'photo'          => null,
                'submitted_by'   => 1,
                'visible'        => true,
            ],
        ];

        foreach ($sights as $sight) {
            $country = Country::where('name', $sight['country'])->first();

            if ($country) {
                if (strtolower(trim($sight['opening_hours'])) === 'open 24 hours') {
                    $sight['opening_hours'] = '24/7';
                }

                Sight::create([
                    'country_id'     => $country->id,
                    'name'           => $sight['name'],
                    'description'    => $sight['description'],
                    'location'       => $sight['location'],
                    'category'       => $sight['category'],
                    'opening_hours'  => $sight['opening_hours'],
                    'average_rating' => $sight['average_rating'] ?? 0,
                    'map_url'        => $sight['map_url'],
                    'photo'          => $sight['photo'],
                    'submitted_by'   => $sight['submitted_by'],
                    'visible'        => $sight['visible'],
                ]);
            }
        }
    }
}
